#:schema https://rtx.pub/schema/rtx.plugin.json

[exec-env]
cache-key = [
  """
  {% if project_root %}
    {{ project_root | canonicalize }}
  {% endif %}
  """,
  """
  {% if opts.virtualenv %}
    {{ opts.virtualenv }}
  {% endif %}
  """
]

[list-bin-paths]
cache-key = [
  """
  {% if project_root %}
    {{ project_root | canonicalize }}
  {% endif %}
  """,
  """
  {% if opts.virtualenv %}
    {{ opts.virtualenv }}
  {% endif %}
  """
]
